load("data/raw/ARI.rda")
load("data/raw/ATL.rda")
load("data/raw/BAL.rda")
load("data/raw/BOS.rda")
load("data/raw/CHC.rda")
load("data/raw/CHW.rda")
load("data/raw/CIN.rda")
load("data/raw/CLE.rda")
load("data/raw/COL.rda")
load("data/raw/DET.rda")
load("data/raw/HOU.rda")
load("data/raw/KCR.rda")
load("data/raw/LAA.rda")
load("data/raw/LAD.rda")
load("data/raw/MIA.rda")
load("data/raw/MIL.rda")
load("data/raw/MIN.rda")
load("data/raw/NYM.rda")
load("data/raw/NYY.rda")
load("data/raw/OAK.rda")
load("data/raw/PHI.rda")
load("data/raw/PIT.rda")
load("data/raw/SDP.rda")
load("data/raw/SEA.rda")
load("data/raw/SFG.rda")
load("data/raw/STL.rda")
load("data/raw/TBR.rda")
load("data/raw/TEX.rda")
load("data/raw/TOR.rda")
load("data/raw/WSN.rda")

games <- rbind(ARI, ATL); rm(ARI, ATL)
games <- rbind(games, BAL); rm(BAL)
games <- rbind(games, BOS); rm(BOS)
games <- rbind(games, CHC); rm(CHC)
games <- rbind(games, CHW); rm(CHW)
games <- rbind(games, CIN); rm(CIN)
games <- rbind(games, CLE); rm(CLE)
games <- rbind(games, COL); rm(COL)
games <- rbind(games, DET); rm(DET)
games <- rbind(games, HOU); rm(HOU)
games <- rbind(games, KCR); rm(KCR)
games <- rbind(games, LAA); rm(LAA)
games <- rbind(games, LAD); rm(LAD)
games <- rbind(games, MIA); rm(MIA)
games <- rbind(games, MIL); rm(MIL)
games <- rbind(games, MIN); rm(MIN)
games <- rbind(games, NYM); rm(NYM)
games <- rbind(games, NYY); rm(NYY)
games <- rbind(games, OAK); rm(OAK)
games <- rbind(games, PHI); rm(PHI)
games <- rbind(games, PIT); rm(PIT)
games <- rbind(games, SDP); rm(SDP)
games <- rbind(games, SEA); rm(SEA)
games <- rbind(games, SFG); rm(SFG)
games <- rbind(games, STL); rm(STL)
games <- rbind(games, TBR); rm(TBR)
games <- rbind(games, TEX); rm(TEX)
games <- rbind(games, TOR); rm(TOR)
games <- rbind(games, WSN); rm(WSN)


# merge with stadium data
colnames(games)[5] <- "Team"
colnames(games)[22] <- "Year"
stadiums <- read.table("data/clean/MLB-Stadium-Capacity.csv", sep=",", header=TRUE, stringsAsFactors=FALSE, nrows=750)
MLBgameData <- merge(x=games, y=stadiums, by=c("Year", "Team"), all.x=TRUE)
rm(games)

save(MLBgameData, file="data/raw/MLBgameData.rda")
